// flow-typed signature: 7c1907a903a1d9a99aed0b4bb3c89751
// flow-typed version: <<STUB>>/web3-core-promievent_v1.0.0-beta.37/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'web3-core-promievent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'web3-core-promievent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'web3-core-promievent/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'web3-core-promievent/src/index.js' {
  declare module.exports: $Exports<'web3-core-promievent/src/index'>;
}
